server:
  port: 80
#  tomcat:
#    uri-encoding: UTF-8
#  ssl:
#    key-store: npblock.cn.jks
#    key-password: 你的密码
#    key-store-type: jks
#    key-alias: npblock.cn
  address: 192.168.1.16
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/npblock?serverTimezone=GMT%2B8&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      initial-size: 5
      min-idle: 5
      max-total: 10
      max-wait-millis: 2000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database: mysql
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true